#
# ax-unix: Alex' UNIX Tools & Scripts
# Copyright (c)2013-2014 Alexander Barton (alex@barton.de)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

SUBDIRS = save-user

include ../Makefile.ax
