#!/usr/bin/env bash
#
# kopia-policy-edit -- Edit the Kopia policy and show the differences
# Copyright (c)2024 Alexander Barton (alex@barton.de)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

set -eu -o pipefail

if [[ $# -ne 0 || "${1:-}" == "--help" ]]; then
	echo "Usage: $0" >&2
	exit 1
fi

echo "Preparing ..."

trap 'rm -f "${tmp1:-}" "${tmp2:-}"' EXIT

tmp1=$(mktemp)
tmp2=$(mktemp)

kopia policy show --global >"$tmp1"
kopia policy edit --global
kopia policy show --global >"$tmp2"

if command -v colordiff >/dev/null; then
	colordiff -u "$tmp1" "$tmp2"
else
	diff -u "$tmp1" "$tmp2"
fi
