#!/usr/bin/env bash
#
# kopia-snapshot -- Generate a Kopia snapshot
# Copyright (c)2024 Alexander Barton (alex@barton.de)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

set -eu -o pipefail

if [[ $# -lt 2 || "${1:-}" == "--help" ]]; then
	echo "Usage: $0 <backend> <path> [<path> [...]]" >&2
	exit 1
fi

# Neither Kopia nor this script is not localized, use the "C" locale for all
# messages of all tools.
export LC_ALL=C

# Execute the kopia(1) binary with all parameters given, collect its output
# and show it on stdout, when no error is signalled, or stderr, when it looks
# like an error occurred.
# The actual exit code of kopia(1) is returned.
run_kopia() {
	set +e
	out=$(kopia "$@" 2>&1)
	result=$?
	set -e
	if [[ $result -eq 0 ]]; then
		echo "$out"
	else
		echo "$out" >&2
		echo "Error, \"kopia $*\" returned with exit code $result!" >&2
	fi
	return $result
}

# HOME may not be set for system services!
[[ -n "${HOME:-}" ]] || export HOME="/root"

backend="$1"
shift

echo "$(date +%c): Connecting to repository \"${backend}\" ..."

token_file="${HOME}/.config/kopia/token-${backend}.config"
if [[ ! -r "${token_file}" ]]; then
	echo "Oops, token file \"${token_file}\" not found! Aborting!" >&2
	exit 1
fi

run_kopia repository connect from-config \
	--no-check-for-updates \
	--token-file="${token_file}"

# Note: we can't use progress output here, even on a terminal, because this
# does not work with the output redirection of run_kopia(), which in turn
# makes sure that errors are properly shown on stderr!
echo "$(date +%c): Starting backup ..."
if run_kopia snapshot create --no-progress "$@"; then
	result=0
	echo "$(date +%c): Backup run done."
else
	result=$?
	echo "$(date +%c): Backup run done, code $result!" >&2
fi
exit $result
